source 'https://rubygems.org'

ruby '2.2.2'
gem 'rails', '4.2.3'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'bootstrap-sass', '~> 3.3.5'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'slim'
gem 'devise'
gem 'rails_12factor'
gem 'friendly_id', '~> 5.1.0'
gem 'simple_form'
gem 'cocoon'
gem 'underscore-rails'

group :development, :test do
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'awesome_print'
  gem 'spring'
  gem 'rspec-rails', '~> 3.0'
end
